export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="false"
unsetopt AUTO_CD

plugins=(git colored-man-pages)

source $ZSH/oh-my-zsh.sh

TERMINAL=foot

export SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt"

export PATH="$PATH:/home/fweichselbaum/.nix-profile/bin"
export PATH="$PATH:/nix/var/nix/profiles/default/bin/"
export PATH="$PATH:/opt/nvim/"
export PATH="$PATH:/opt/fzf/"
export PATH="$PATH:/opt/lazygit/"

alias py='python3'
alias dcu='docker compose up'
alias dcub='docker compose up --build'
alias dcud='docker compose up -d'
alias dcd='docker compose down'
alias dcrm='docker container rm'
alias dirm='docker image rm'
alias j='z'
alias jj='zi'
alias fd='fdfind'
alias cnvim='nvim ~/.config/nvim/'
alias bat="batcat"
alias lla="ll -a"

eval "$(zoxide init zsh)"
source <(fzf --zsh)

. "$HOME/.local/bin/env"
